boardgame-tournament:
        image: omnibrain/boardgame-tournament:latest
        ports:
                - "7777:80"
        links:
                - mongodb
        environment:
                MONGODB_HOST: mongodb
mongodb:
        image: mongo


