boardgame-tournament:
        build: .
        ports:
                - "80:80"
        links:
                - mongodb
        environment:
                MONGODB_HOST: mongodb
mongodb:
        image: mongo
        container_name: mongodb


